config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :tiktok)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div>
    <%= form.label :tiktok, style: "display: block" %>
    <%= form.text_field :tiktok, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary mt-5" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">

  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">First Name</label>
    <div class="col-sm-10">
    <label for="staticEmail" class="col-sm-2 col-form-label"><%= friend.first_name %></label>
    </div>
  </div>

  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Last Name</label>
    <div class="col-sm-10">
      <label for="staticEmail" class="col-sm-2 col-form-label"><%= friend.last_name  %></label>
    </div>
  </div>

  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <label for="staticEmail" class="col-sm-2 col-form-label"><%= friend.email  %></label>
    </div>
  </div>

  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Phone</label>
    <div class="col-sm-10">
      <label for="staticEmail" class="col-sm-2 col-form-label"><%= friend.phone  %></label>
    </div>
  </div>

  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Tiktok</label>
    <div class="col-sm-10">
      <label for="staticEmail" class="col-sm-2 col-form-label"><%= friend.tiktok  %></label>
    </div>
  </div>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend,  class: "btn btn-success mt-5" %> 
  <%= link_to "Back to friends", friends_path, class: "btn btn-outline-secondary mt-5" %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1> 
<%= link_to "New friend", new_friend_path, class:"btn btn-success mb-3" %>

<div id="friends">

  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Tiktok</th>
      <th scope="col" colspan="2"> Action  <i class="bi bi-gear-fill"></i> </th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <th scope="row"></th>
        <td> <%= friend.first_name+" "+friend.last_name %>  </td>
        <td> <%= friend.email %> </td>
        <td> <%= friend.phone %> </td>
        <td> <%= friend.tiktok %> </td>
        <td> <%= link_to "Show", friend, class:"btn btn-primary text-center" %> <td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Kembali", friends_path, class: "btn btn-outline-secondary" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) , class: "btn btn-primary mt-5"%> 
  <%= link_to "Back to friends", friends_path,  class: "btn btn-outline-secondary mt-5" %>

  <%= button_to "Destroy this friend", @friend, method: :delete , class: "btn btn-danger mt-5" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg ">
    <%= link_to 'Friend Apps', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>
        </ul>
        <span class="navbar-text">
        Muhamad Ridwan
        </span>
    </div>
</nav>

app/views/home/about.html.erb
<h3 class="text-primary">This is About page </h3>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <title>Hello, world!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'home/header' %>
    <div class="container"><br/>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>